---
namespace: cfmm
name: keycloak
version: "1.0.7"
readme: README.md
authors:
  - Romain Pelisse <rpelisse@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
  - Pavan Kumar Motaparthi <pmotapar@redhat.com>
description: Install and configure a keycloak, or Red Hat Single Sign-on, service.
license_file: "LICENSE"
tags:
  - keycloak
  - redhat
  - rhel
  - sso
  - openid
  - application
  - identity
  - security
  - infrastructure
  - authentication
dependencies:
  "middleware_automation.redhat_csp_download": ">=1.2.1"
  "middleware_automation.wildfly": ">=1.0.0"
repository: https://github.com/isolovey/keycloak
documentation: https://ansible-middleware.github.io/keycloak
homepage: https://github.com/isolovey/keycloak
issues: https://github.com/ansible-middleware/keycloak/issues
build_ignore:
  - molecule
  - .github
  - '*.tar.gz'
  - '*.zip'
  - changelogs/fragments/.gitignore
