---
collections:
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: community.general
  - name: ansible.posix
  - name: git+git@git.cfmm.uwo.ca:ansible/general.git
    type: git
    version: main

