---
keycloak:
  home: "{{ keycloak_quarkus_home }}"
  config_dir: "{{ keycloak_quarkus_config_dir }}"
  bundle: "{{ keycloak_quarkus_archive }}"
  service_name: "keycloak"
  health_url: "{{ keycloak_quarkus_health_url }}"
  cli_path: "{{ keycloak_quarkus_home }}/bin/kcadm.sh"
  service_user: "{{ keycloak_quarkus_service_user }}"
  service_group: "{{ keycloak_quarkus_service_group }}"
  log:
    file: "{{ keycloak_quarkus_home }}/{{ keycloak_quarkus_log_file }}"
    level: "{{ keycloak_quarkus_log_level }}"
    format: "{{ keycloak_quarkus_log_format }}"
