---
# tasks file for keycloak
- name: Check prerequisites
  ansible.builtin.include_tasks: prereqs.yml
  tags:
    - prereqs

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: Create systemd service
  ansible.builtin.include_role:
    name: cfmm.general.systemd
    public: no
  vars:
    systemd_task_user: '{{ keycloak.service_user }}'
    systemd_task_group: '{{ keycloak.service_group }}'
    systemd_task_command: '{{ keycloak.home }}/bin/kc.sh start --auto-build'
    systemd_task_wantedby:
      - multi-user.target
    systemd_task_timeout_start_sec: 600
    systemd_task_timeout_stop_sec: 600
    systemd_task_type: simple
    systemd_task: keycloak
    systemd_restart: no
    systemd_after:
      - network.target
    systemd_task_environment:
      - name: KEYCLOAK_ADMIN
        value: "{{ keycloak_quarkus_admin_user }}"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "{{ keycloak_quarkus_admin_pass }}"
      - name: JAVA_OPTS_APPEND
        value: "-Djgroups.mcast_addr={{ keycloak_quarkus_jgroups_mcast_addr }} \
        -Djgroups.bind_addr={{ keycloak_quarkus_jgroups_bind_addr }}"
  tags:
    - systemd

- name: "Configure config for keycloak service"
  ansible.builtin.template:
    src: keycloak.conf.j2
    dest: "{{ keycloak.home }}/conf/keycloak.conf"
    owner: "{{ keycloak.service_user }}"
    group: "{{ keycloak.service_group }}"
    mode: 0644
  become: yes
  notify:
    - restart keycloak

- name: "Configure quarkus config for keycloak service"
  ansible.builtin.template:
    src: quarkus.properties.j2
    dest: "{{ keycloak.home }}/conf/quarkus.properties"
    owner: "{{ keycloak.service_user }}"
    group: "{{ keycloak.service_group }}"
    mode: 0644
  become: yes
  notify:
    - restart keycloak

- name: Ensure logdirectory exists
  ansible.builtin.file:
    state: directory
    path:  "{{ keycloak.log.file | dirname }}"
    owner: "{{ keycloak.service_user }}"
    group: "{{ keycloak.service_group }}"
    mode: 0775
  become: yes

- name: "Start and wait for keycloak service"
  ansible.builtin.include_tasks: start.yml

- name: Check service status
  ansible.builtin.command: "systemctl status keycloak"
  register: keycloak_service_status
  changed_when: False

- name: Link default logs directory
  ansible.builtin.file:
    state: link
    src: "{{ keycloak.log.file | dirname }}"
    dest: /var/log/keycloak
    force: yes
  become: yes
